use_frameworks!

platform :ios, '10.0'

target 'MobilliumToolTips_Example' do
  pod 'MobilliumToolTips', :path => '../'

  target 'MobilliumToolTips_Tests' do
    inherit! :search_paths

    
  end
end
